#!/usr/bin/env python3
"""P1.6 evidence-based CandidateProvider decision, with no runtime changes."""
from __future__ import annotations

import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
REPORTS = ROOT / "app/build/reports"
ENGINE = ROOT / "app/src/main/java/com/rabpit/backroom/core/knowledge/KnowledgeContextEngine.kt"
OUTPUT = REPORTS / "canon-p1/candidate-provider-decision.json"
PASSES = [
    "addMandatory", "addCurrentLevel", "addPresentRuntimeCards",
    "addRelationships", "addDirectStructuredLookups", "addSceneAffordances",
    "addStateDrivenRecords", "expandReferences",
]


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> None:
    # ENGINE is already final-generated by the production patch chain.
    code = ENGINE.read_text(encoding="utf-8")
    start = code.index("    fun build(): String {", code.index("private class Builder("))
    stop = code.index("      val records = budgetedRecords()", start)
    actual_passes = re.findall(
        r"^\s+(" + "|".join(PASSES) + r")\(\)", code[start:stop], re.MULTILINE
    )
    assert actual_passes == PASSES, (actual_passes, PASSES)
    required_runtime_markers = [
        "selected.putIfAbsent(id, record)",
        "reasons.putIfAbsent(id, reason)",
        "val visited = selected.keys.toMutableSet()",
        "if (!visited.add(id))",
        "LEGACY_REFERENCE_PRIORITY_GATE",
        "it.priority <= 30",
        "it.priority > 30",
        '"LEVEL.%02d".format(Locale.ROOT, number)',
        'r.domain == "ENTITY" || r.domain == "ITEM"',
        "db.tagIndex.entries.asSequence()",
        'direct += "CHAR.IRIS.ARGUS"',
        'if ("iris" in presentActors)',
        'if ("syvial" in presentActors)',
    ]
    for marker in required_runtime_markers:
        assert marker in code, f"Final runtime changed; review decision: {marker}"
    p0 = read_json(REPORTS / "canon-p0/snapshot-report.json")
    shadow_dir = REPORTS / "canon-p1"
    reference = read_json(shadow_dir / "reference-shadow.json")
    alias = read_json(shadow_dir / "alias-shadow.json")
    tier = read_json(shadow_dir / "tier-shadow.json")
    compiler_data = read_json(shadow_dir / "compiler-data-parity.json")
    compiler_runtime = read_json(shadow_dir / "compiler-runtime-parity.json")
    assert p0["scenarioCount"] == tier["scenarioCount"] == compiler_runtime["scenarioCount"] == 25
    assert reference["legacyReferencePriorityGate"] == tier["legacyReferencePriorityGate"] == 55
    assert alias["tagOnlyCases"] == alias["aliasOnlyCases"] == 0
    assert alias["parityCases"] == alias["caseCount"]
    assert compiler_data["passed"] and compiler_runtime["packetParityCount"] == 25
    assert all(x["packetSha256"] == x["shadowPacketSha256"] for x in tier["scenarios"])

    report = {
        "schemaVersion": 1,
        "mode": "decision_only",
        "decision": "NOT_NEEDED_NOW",
        "source": "final_generated_KnowledgeContextEngine_after_production_patch_chain",
        "selectionStages": {
            "orderedPassCount": len(actual_passes),
            "candidateRegistrationPassCount": len(actual_passes) - 1,
            "referenceExpansionPassCount": 1,
            "independentlyPluggableProviderCount": 0,
            "passes": actual_passes,
            "interpretation": (
                "Ordered Builder passes exist, but none is an independent provider boundary: "
                "all register through a shared selected/reasons set; reference expansion "
                "depends on the union and budgeting consumes the union."
            ),
        },
        "newRecordActivation": {
            "CHARACTER": {
                "centralSelectionChangeRequired": True,
                "scope": "New present actors/character-specific abilities or relationships",
                "evidence": ["named presence gates", "named character direct branches", "named relationships"],
            },
            "ENTITY": {
                "centralSelectionChangeRequired": False,
                "scope": "Direct action lookup when a reviewed runtime tag exists",
                "caveat": "New state-driven automatic activation may still require code.",
            },
            "ITEM": {
                "centralSelectionChangeRequired": False,
                "scope": "Direct action lookup when a reviewed runtime tag exists",
                "caveat": "New item-specific gameplay behavior is outside this lookup guarantee.",
            },
            "LEVEL": {
                "centralSelectionChangeRequired": False,
                "scope": "Numeric LEVEL.%02d IDs resolved from current level state",
                "caveat": "The current level is clamped to 0..999; non-numeric/novel routing is not supported.",
            },
        },
        "orderingAndSharedStateRisks": [
            {
                "mechanism": "selected.putIfAbsent / reasons.putIfAbsent",
                "risk": "First successful candidate reason wins; reordering passes can change packet why text.",
            },
            {
                "mechanism": "reference BFS from selected insertion order / shared visited set",
                "risk": "Split provider order can change traversal, already_visited decisions and reference expansion.",
            },
            {
                "mechanism": "priority-and-ID-sorted budgeting after shared selection",
                "risk": "Sorting stabilizes kept record order but does not make candidate/reason/visited behavior independent.",
            },
            {
                "mechanism": "presence/affordance/shared actor gates",
                "risk": "Character and scene contributions depend on shared state and actor eligibility.",
            },
        ],
        "shadowEvidence": {
            "p0ScenarioCount": p0["scenarioCount"],
            "tierScenarioCount": tier["scenarioCount"],
            "legacyReferenceGate": reference["legacyReferencePriorityGate"],
            "referenceEdgeCount": reference["edgeCount"],
            "aliasCaseCount": alias["caseCount"],
            "aliasOnlyCases": alias["aliasOnlyCases"],
            "tagOnlyCases": alias["tagOnlyCases"],
            "compilerDataParityPassed": compiler_data["passed"],
            "compilerRuntimeParityScenarios": compiler_runtime["packetParityCount"],
        },
        "rationale": [
            "Entity/Item exact tag lookup and numeric Level lookup already work without a new provider abstraction.",
            "Character onboarding still has named central gates, but P0/P1 evidence does not demonstrate multiple independent provider implementations.",
            "Alias and reference shadows are observational; neither has introduced independent candidate semantics.",
            "Refactoring the shared selection/reason/reference order would create packet parity risk without a demonstrated current need.",
        ],
        "futureChangeCandidate": (
            "Reconsider a provider boundary only after a real new activation source requires it "
            "and P0 byte parity plus ordering/reference behavior can be preserved."
        ),
        "proposedBoundary": None,
        "interfaceImplemented": False,
        "runtimeCutover": False,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("Canon P1.6 decision:", report["decision"], "passes=", len(actual_passes),
          "independent_providers=0")


if __name__ == "__main__":
    main()
